### ISSUE TITLE
 The first and the last item scroll to center question?

### ISSUE THREAD

**Issue by MIkeeJY** [Pixplicity/MultiViewPager#7] opened 2015-07-22 05:37 UTC
I need to remove the padding from each items.. And if the index of the item is 0,I need to make it to  screen's leff ! I don't wanna let the first  view scroll to center in screen..
Just like this: 
![qq 20150722140758](https://cloud.githubusercontent.com/assets/8580762/8819080/54d2d958-307b-11e5-92a2-896d4f00ba9e.jpg)

![20150722134625](https://cloud.githubusercontent.com/assets/8580762/8818876/f3f50108-3078-11e5-8c64-a394ca6bf62d.png)

In a simple word,I don't want the first and the last item scroll in center..

.Tell me how to do it...Thankls a lot..

**Comment by pflammertsma** [comment] 2015-07-31 18:08
If I understand this issue correctly, it is a duplicate of #2. Please see my comments there.

**Closed as completed by pflammertsma** 2015-07-31 18:08 UTC
Labels: duplicate
